- src/hooks/useScrollCountup.tsx
- src/hooks/useScrollFadeIn.tsx
- src/pages/home.tsx
- src/styles/main5Styles.css
-[ㅇ] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
메인 페이지에 CountUp Aniamtion을 추가했습니다
(`useScrollCountup` Hook을 추가했습니다)
> CountUp Animation

- public/sitemap.xml
- src/components/foot.tsx
- src/pages/home.tsx
PR 타입
-[] 기능 추가
-[ㅇ] 기능 수정
-[] 기능 삭제
-[] 버그 수정
-[ㅇ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
변경 사항
public directory에 sitemap.xml 파일을 추가했습니다.
Countup 세부사항(수치)을 수정했습니다.
> CountUp details and sitemap.xml

- public/index.html
added font size to fix screen rem
> added font size to fix screen rem

- public/manifest.json
manifest파일에 icons을 기존 react 로고에서 doro 로고로 수정
> style: manifest.js icons(favicon) 수정

- public/manifest.json
Reverts dojeonrobot/Doro-frontend#82
> Revert "style: manifest.js icons(favicon) 수정"

- public/index.html
- src/pages/404.tsx
- src/pages/posts.tsx
- src/styles/bannerStyles.css
- src/styles/createStyles.css
- src/styles/footStyles.css
- src/styles/headerStyles.css
- src/styles/main1Styles.css
- src/styles/main2Styles.css
- src/styles/main4Styles.css
- src/styles/main5Styles.css
- src/styles/main7Styles.css
- src/styles/main8Styles.css
- src/styles/postStyles.css
- 각 페이지에 있던 min-width 속성 삭제
- index.html 파일 html 태그에 min-width 속성 추가
> refact: min-width 속성 통합

- public/index.html
- src/styles/main1Styles.css
> style: 화면비율 테스트

- public/index.html
> style: min-width 조절

- src/components/mainEduContent.tsx
- 대표 교육 컨텐츠 호버시 글자 움직이는 문제
- 메인 배너 이미지 수정 - 로딩 시간 이슈
> fix: 메인 페이지 이슈 수정

- package-lock.json
- package.json
- src/__generated__/SendAuthNum.ts
- src/__generated__/checkAuthNumQuery.ts
- src/__generated__/createEdu.ts
- src/__generated__/globalTypes.ts
- src/components/header.tsx
- src/index.tsx
- src/pages/applyNewEducation.tsx
- src/pages/createEdu.tsx
- src/pages/home.tsx
- src/routers/logged-in-router.tsx
- src/routers/logged-out-router.tsx
- src/styles/createEdu.css
- 카카오톡 인증 관련 추가
- multiple date picker 추가
> feat: 교육 신청 페이지 수정 

- src/components/mainEduType.tsx
* 메인페이지 '교육수행유형' 이미지 로딩 지연 현상 해결
> fix: 메인페이지 '교육수행유형' 이미지 로딩 지연 현상 해결

- src/components/DoroInstructor.tsx
- src/components/EduDetailContents.tsx
- src/components/header.tsx
- src/components/mainEduContent.tsx
- src/components/mainEduType.tsx
- src/pages/home.tsx
- src/pages/showDetailContent.tsx
- src/styles/eduContentStyles.css
> fix: 메인페이지 & 콘텐츠페이지 수정

- src/components/DoroInstructor.tsx
- src/components/EduDetailContents.tsx
- src/components/mainEduContent.tsx
- src/pages/home.tsx
* '전공지식 갖춘 대학 강사' hover -> overflow: hidden 적용 (마우스 올렸을 때 글자 박스가 이미지(강사 이미지) 박스안에서만 나타나도록 수정
* 훈님 수정사항 merge
> fix: '전공지식 갖춘 대학 강사' hover -> overflow: hidden 적용 외 1가지

- src/components/EduDetailContents.tsx
- src/components/mainEduType.tsx
- src/index.tsx
* feat: DORO 교육 수행 유형 - 교육 콘텐츠 링크 연결
> feat: DORO 교육 수행 유형 - 교육 콘텐츠 링크 연결

- src/components/EduDetailContents.tsx
- src/components/mainEduContent.tsx
- src/pages/home.tsx
* feat: [메인페이지] Doro 대표 교육 콘텐츠 -> 콘텐츠 페이지 링크 추가
* feat: [메인페이지] DORO 메이킹 7종 키트 라우터 추가
> feat: [메인페이지] Doro 대표 교육 콘텐츠 라우터 추가 외 1개

- src/components/EduDetailContents.tsx
* fix: [교육 콘텐츠 페이지] 카테고리 자동 실행 X 부분 해결
> fix: [교육 콘텐츠 페이지] 카테고리 자동 실행 X 부분 해결

- src/pages/makeNewApplication.tsx
- src/styles/makeNewApplication.css
> feat: [교육 신청 페이지] 왼쪽 배너 구현

- src/__generated__/createEdu.ts
- src/pages/makeNewApplication.tsx
- src/pages/showApplication.tsx
- src/styles/createStyles.css
- src/styles/makeNewApplication.css
* 질문 파트 별 다음 버튼 눌렀을 때 다음 질문 입력할 수 있도록 열리는 부분 애니메이션
*  따라다니는 왼쪽 배너 추가
*  카카오톡 인증 버튼 눌렀을 때 번호 입력하는 버튼 & 인증하기 버튼 생기게 수정
*  전송 시 알림창 - 모달
* 카카오톡 인증 버튼 눌렀을 때 시간 생성
> feat: [신청 페이지] 왼쪽 프로그래스바 외 4가지 추가

- src/components/scrollToTop.tsx
- src/routers/logged-in-router.tsx
- src/routers/logged-out-router.tsx
> fix: 페이지 렌더링 시 스크롤 최상단

- src/components/EduDetailContents.tsx
* fix: 메인페이지 header 통해 교육콘텐츠 이동할 때 오류 해결
> fix: 메인페이지 header 통해 교육콘텐츠 이동할 때 오류 해결

- src/pages/makeNewApplication.tsx
* fix: [교육신청페이지] 질문 폼 렌더링 문제 수정
> fix: [교육신청페이지] 질문 폼 렌더링 문제 수정

- src/pages/makeNewApplication.tsx
[Feat: 유효성 검사에 따른 버튼 활성화 기능 추가]
[Feat: 교육 신청 마지막 페이지에서 인풋 값 수정 불가능하게 설정]
> 교육 신청 페이지 버튼 활성화 및 수정 제한

- src/components/EduDetailContents.tsx
* fix: [콘텐츠페이지] 첫 렌더링 시 카테고리 뜨지 않는 현상 해결
> fix: [콘텐츠페이지] 첫 렌더링 시 카테고리 뜨지 않는 현상 해결

- src/pages/editApplication.tsx
- src/pages/showApplication.tsx
create -> edit으로 변경
findoverall class 후 refetch로 cahce 업데이트
> <fix> : <editApplication 수정기능 추가>

- src/pages/editApplication.tsx
- src/pages/showApplication.tsx
edit후 main으로 가고 cache업데이트를 위한 새로고침 추후 수정 필요
> <fix>:<edit기능 수정>

- src/__generated__/FindOverallClass.ts
- src/__generated__/globalTypes.ts
- src/pages/editApplication.tsx
- src/pages/makeNewApplication.tsx
> fix: 매칭페이지 타입 string으로 변경

- src/pages/editApplication.tsx
- src/pages/makeNewApplication.tsx
* fix: 매칭페이지 input 타입 string 변경 재수정
> fix: 매칭페이지 input 타입 string 변경 재수정

- src/pages/makeNewApplication.tsx
> fix: [매칭페이지] 다음 버튼 제어 수정

- package-lock.json
- package.json
- src/__generated__/FindOverallClass.ts
- src/__generated__/globalTypes.ts
- src/pages/editApplication.tsx
- src/pages/makeNewApplication.tsx
- yarn.lock
* fix: [매칭페이지] - 교육 날짜 로드 오류 수정
> fix: [매칭페이지] - 교육 날짜 로드 오류 수정

- src/pages/home.tsx
> fix: 메인페이지 강의 누적 교육생 값  수정

- src/pages/home.tsx
- src/pages/posts.tsx
- src/pages/user/login.tsx
> test: token 확인 및 로그인 페이지 메모

- src/pages/showApplication.tsx
> test: 로그인 확인

- src/pages/home.tsx
- src/pages/showApplication.tsx
- src/pages/user/login.tsx
* feat: [매칭page] - 관리자 정보 열람 기능 추가 외 1개
* style: 필요없는 console.log 삭제
> feat: [매칭page] - 관리자 정보 열람 기능 추가 외 1개

- package-lock.json
- package.json
- src/hooks/history.ts
- src/pages/editApplication.tsx
- src/pages/makeNewApplication.tsx
- src/styles/retrieveStyles.css
- yarn.lock
[매칭page]
* 신청내역 글자 위치 교정
* 학급별 교육 일정 첫 항목 삭제 방지
> [매칭page] - 신청내역 글자 위치 교정, 학급별 교육 일정 첫 항목 삭제 방지

- src/pages/createPost.tsx
- src/pages/editApplication.tsx
- src/pages/editPost.tsx
- src/pages/makeNewApplication.tsx
- src/pages/post.tsx
- src/pages/posts.tsx
- src/pages/showApplication.tsx
* fix: 교육 특이사항 줄바꿈 수정
* style: console 주석 처리
> fix: 교육 특이사항 줄바꿈 수정 외 1개

- src/pages/editApplication.tsx
- src/pages/makeNewApplication.tsx
- src/pages/showApplication.tsx
* fix: 교육 신청, 수정 후 applyEdu로 이동
* fix: 교육 신청내역 수정 오류 수정
> fix: 교육 신청, 수정 후 applyEdu로 이동, 교육 신청내역 수정 오류 수정

- src/components/applyButton.tsx
- src/pages/editApplication.tsx
- src/pages/makeNewApplication.tsx
- src/styles/makeNewApplication.css
> fix 교육 신청 모달 내용 수정

- src/components/EduDetailContents.tsx
- src/styles/eduContentStyles.css
> feat: 교육콘텐츠 호버링 추가
